### PR TITLE
Fix bug in ESSC.py causing example file to crash

### LINKED ISSUE #31: Error: example_envSampling when data is from buoy46022.fetchFromWeb()
I used the `buoy46022.fetchFromWeb()`  option when running `example_envSampling.py`.

When doing so I saw more than 10 `RuntimeWarning: underflow encounter`.

Eventually the example errors with:
`TypeError: only size-1 arrays can be converted to Python scalars`

@zmorrell-sand can you comment on this error?

observed warning/error stack below

```bash
PS C:\Users\sterl_000\Codes\WDRT\tests> python .\example_envSampling.py
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w1996.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w1997.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w1998.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w1999.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2000.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2001.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2002.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2003.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2004.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022wb2004.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2005.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2006.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2007.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2008.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2009.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2010.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2011.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2012.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2013.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2014.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2015.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2016.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2017.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2018.txt.gz&dir=data/historical/swden/
Reading from: https://www.ndbc.noaa.gov/view_text_file.php?filename=46022w2019.txt.gz&dir=data/historical/swden/
c:\users\sterl_000\codes\wdrt\WDRT\ESSC.py:819: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  mean_cond = np.linalg.lstsq(phi_mean,para_dist_cond[:,0])[0]
c:\users\sterl_000\codes\wdrt\WDRT\ESSC.py:821: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  std_cond = np.linalg.lstsq(phi_std,para_dist_cond[:,1])[0]
C:\Users\sterl_000\anaconda3\lib\site-packages\statsmodels\nonparametric\kdetools.py:35: RuntimeWarning: underflow encountered in exp
  FAC = np.exp(-JFAC)/BC
C:\Users\sterl_000\anaconda3\lib\site-packages\statsmodels\nonparametric\kdetools.py:35: RuntimeWarning: underflow encountered in true_divide
  FAC = np.exp(-JFAC)/BC
C:\Users\sterl_000\anaconda3\lib\site-packages\statsmodels\nonparametric\kde.py:494: RuntimeWarning: underflow encountered in multiply
  zstar = silverman_transform(bw, gridsize, RANGE)*y # 3.49 in Silverman
C:\Users\sterl_000\anaconda3\lib\site-packages\statsmodels\sandbox\nonparametric\kernels.py:520: RuntimeWarning: underflow encountered in exp
  np.exp(-x**2/2.0), h = h, domain = None, norm = 1.0)
C:\Users\sterl_000\anaconda3\lib\site-packages\statsmodels\sandbox\nonparametric\kernels.py:520: RuntimeWarning: underflow encountered in multiply
  np.exp(-x**2/2.0), h = h, domain = None, norm = 1.0)
C:\Users\sterl_000\anaconda3\lib\site-packages\statsmodels\sandbox\nonparametric\kernels.py:204: RuntimeWarning: underflow encountered in multiply
  w = 1. / (h * n) * np.sum(self((xs-x)/h), axis=0)
c:\users\sterl_000\codes\wdrt\WDRT\ESSC.py:858: RuntimeWarning: underflow encountered in true_divide
  F_hs = tempPDF/sum(tempPDF)
c:\users\sterl_000\codes\wdrt\WDRT\ESSC.py:862: RuntimeWarning: underflow encountered in true_divide
  F_t = f_t/sum(f_t)
c:\users\sterl_000\codes\wdrt\WDRT\ESSC.py:2516: RuntimeWarning: underflow encountered in multiply
  p_x2_x1 = Y*self.nonpara_pdf_2[:,1]
C:\Users\sterl_000\anaconda3\lib\site-packages\scipy\stats\_continuous_distns.py:180: RuntimeWarning: underflow encountered in exp
  return np.exp(-x**2/2.0) / _norm_pdf_C
C:\Users\sterl_000\anaconda3\lib\site-packages\scipy\stats\_continuous_distns.py:180: RuntimeWarning: underflow encountered in true_divide
  return np.exp(-x**2/2.0) / _norm_pdf_C
c:\users\sterl_000\codes\wdrt\WDRT\ESSC.py:2682: RuntimeWarning: underflow encountered in multiply
  ftemp = np.multiply(ftemp,fnew)
c:\users\sterl_000\codes\wdrt\WDRT\ESSC.py:2678: RuntimeWarning: underflow encountered in multiply
  fnew = fk*(1/np.transpose(xi[j][i]))
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\example_envSampling.py", line 71, in <module>
    plt.plot(logKDE_T_Return, logKDE_Hs_Return, 'b--', label = 'Bivariate KDE (log)')
  File "C:\Users\sterl_000\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2796, in plot
    is not None else {}), **kwargs)
  File "C:\Users\sterl_000\anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 1667, in plot
    self.add_line(line)
  File "C:\Users\sterl_000\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 1902, in add_line
    self._update_line_limits(line)
  File "C:\Users\sterl_000\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 1924, in _update_line_limits
    path = line.get_path()
  File "C:\Users\sterl_000\anaconda3\lib\site-packages\matplotlib\lines.py", line 1027, in get_path
    self.recache()
  File "C:\Users\sterl_000\anaconda3\lib\site-packages\matplotlib\lines.py", line 670, in recache
    x = _to_unmasked_float_array(xconv).ravel()
  File "C:\Users\sterl_000\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 1390, in _to_unmasked_float_array
    return np.asarray(x, float)
  File "C:\Users\sterl_000\anaconda3\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
PS C:\Users\sterl_000\Codes\WDRT\tests>
```

### PR DESCRIPTION
**Pull request by zmorrell-sand**
Removed a slice operation and un-commented two lines that transposed the return values in the ESSC.getContours function to make plotting work.

### CODE REVIEW

**Comment by ssolson** [comment]
Zach I still get the no dateList issue. See #29

**Comment by zmorrell-sand** [comment]
@ssolson 
Sorry, I posted the fix in the wrong bug thread.  This fixes the fetchFromWeb bug.  I will look into the h5 bug right now

**Comment by ssolson** [comment]
closes #31

**Review by ssolson — APPROVED** [review]
This successfully allows the user to pull data from Web and closes #31. I am going to merge this. @zmorrell-sand please submit a new PR to  address #29

**Pull request merged**
